### ISSUE TITLE
Consider exposing a ParseT transformer version

### ISSUE THREAD

**Issue by dylex** [hdgarrood/aeson-better-errors#2]
This library looks really useful, similar to things I've had to build simpler versions of.  Have you considered exposing a generalized monad transformer version of something like:
```
newtype ParseT err m a = ParseT (ReaderT ParseReader (ExceptT (ParseError err) m) a)
type Parse err a = ParseT err Identity a
```
This would make it useful in many forms of online json processing, while keeping the pure interface as a special-case.

**Comment by hdgarrood** [comment]
Interesting, no I hadn't considered that. Can you give an example of what you might use it for?

**Comment by dylex** [comment]
Whenever you're simultaneously processing a json object and doing something with it. For example, we use json to ingest data to a database. We know the json is generally valid because it's already been run through a schema validator, and have no reason to produce an intermediate representation of the json, but do want to process its contents, updating the database in the process, and producing contextual error messages (which aren't necessarily parsing errors) that include the path when something goes wrong.  Essentially we just want to parse the json in the context of another monad.

A simpler case would just be where there's some other context that informs parsing, such as a symbol table or incrementally constructed data structure.  When writing parsers in other contexts, especially for languages, this is quite common.  Parsec itself defines a `ParsecT` transformer like this.

**Comment by hdgarrood** [comment]
Yeah ok, sounds good. I'll happily review a pull request for this, but I probably won't get around to implementing it any time soon.
