### ISSUE TITLE
Type class

### ISSUE THREAD

**Issue by phadej** [hdgarrood/aeson-better-errors#4]
Walked into this, and wondering why there aren't type class?

```hs
class FromJSONBE a where
  parseJSONBE :: Parse e a

instance FromJSONBE String where
  parseJSONBE = asString

instance FromJSONBE Int where
  parseJSONBE = asIntegral

instance FromJSON a => FromJSONBE [a] where
  parseJSONBE = eachInArray parseJSONBE

instance (FromJSONBE a, FromJSONBE b) => FromJSONBE (a, b) where
  parseJSONBE = (,) <$> nth 0 parseJSONBE <*> parseJSONBE

key' :: FromJSONBE a => Text -> Parse e a
key' name = key name parseJSONBE
```

Then examples in http://harry.garrood.me/blog/aeson-better-errors/ could be rewritten as

```hs
asPerson :: Parse e Person
asPerson = Person <$> key' "name" <*> key' "age"

asPerson' :: Parse e Person
asPerson' = Person . curry <$> parseJSONBE

asClass :: Parse e Class
asClass =
  Class <$> key' "teacher"
        <*> key' "students"
```

IMHO it could save some typing when schema is somehow sane

**Comment by hdgarrood** [comment]
This is a deliberate omission, and there are four reasons:

* Many types, both those in base and user-defined ones, do not have just one way of being serialized. You might prefer to serialize `(Foo, Bar)` as `object [ "foo" .= fst, "bar" .= snd ]`, for example.
* It's far too easy to write something that type checks fine and does the completely wrong thing. For example, if I want to get a `[(Text, a)]` out of a JSON object such as `"dependencies": {"foo": "1.0", "bar": "2.0"}` , it's too easy to just write `parseJSON`, which would not work. It would probably expect something like `[["foo", "1.0"], ["bar", "2.0"]]` instead.
* Parser code that relies on type classes is difficult to read. You have to keep referring back to the type to work out what it's going to do. In comparison, it is possible to work out what these parsers will do without having to refer to any other part of your code.
* You often want to parameterize your parsers based on values obtained at runtime. For example, `purescript` has a parser for PureScript packages that is parameterized on the minimum allowable compiler version that is expected. It's very awkward, often impossible, to achieve the same using newtypes.

If the benefit of a type class is that it saves typing, I don't think that's a good enough reason.

**Comment by phadej** [comment]
For me type class and direct combinators aren't mutually exclusive. When you need to be specific, you can be. E.g. have it defined in a separate module. 

Thanks to explaining the reasoning though. It might be worth adding to the documentation.

**Comment by hdgarrood** [comment]
Of course, they can both exist, but I'd rather not have type classes at all inside this package.

No problem re explaining. I'm not sure the documentation is the right place but if I get around to it, I might write something up expanding on this and put it somewhere.
