### ISSUE TITLE
Consider adding variant of eachInObjectWithKey

### ISSUE THREAD

**Issue by dylex** [hdgarrood/aeson-better-errors#5]
What about a function `forEachInObject :: (Text -> Parse err a) -> Parse err [a]` that passed the key to the inner parser, so that you could parse the value dependent on the key? I'm not sure the right name for it, though.

**Comment by hdgarrood** [comment]
Hm, feels quite specific. Can you work out a way to implement this in terms of the current API, or perhaps to generalize this idea at all?

**Comment by dylex** [comment]
I couldn't figure out a good way to do this without just calling `asObject` and parsing it manually, though this loses the nice error messages.  I have also felt the need for an `asValue :: Parse err Value` that just returns the current JSON value (we have a number of values that can be multiple types and I've head to use `catchError`), which could provide a similar approach.

I suppose you could use `asObject`, manually parse, and in parallel call `key` but this feels ugly.  Implementing `forEachInObject` seems like the more general solution, since then you could implement `eachInObject` and `eachInObjectWithKey` very simply in terms of it, like https://github.com/dylex/aeson-better-errors/commit/6eaf12b0178f7ef67b2ba93bb0745eb8b87aa69f

**Comment by hdgarrood** [comment]
Ok, that makes sense.

**Comment by dylex** [comment]
If you're okay with the name (I didn't have any better ideas `forEachInObject` since `eachInObjectWithKey` is taken) I can document it and send a PR.

**Comment by hdgarrood** [comment]
`forEachInObject` is fine I think.
